export const ACTION_TYPES = {
  GAME_START: "GAME_START",
  GAME_EXIT: "GAME_EXIT",

  GAME_WIDTH_CHANGE: "GAME_WIDTH_CHANGE",
  GAME_HEIGHT_CHANGE: "GAME_HEIGHT_CHANGE",
  GAME_STEPS_COUNT_CHANGE: "GAME_STEPS_COUNT_CHANGE",
};
